#!/bin/bash

# detecting files
FILES_SPEC="$(ls *.spec 2>/dev/null)"
FILES_DEBIAN="$(ls */debian 2>/dev/null)"

if [ -n "${FILES_SPEC}" ]; then
  echo "Detected RPM source: ${FILES_SPEC}"
  echo
  echo "[ running source build ]"
  icinga-build-rpm-source
  if [ $? -ne 0 ]; then
    echo "[ source build failed! ]"
    exit 1
  fi
  echo "[ source build completed ]"
  echo
  echo "[ running binary build ]"
  icinga-build-rpm-binary
  if [ $? -ne 0 ]; then
    echo "[ binary build failed! ]"
    exit 1
  fi
  echo "[ binary build completed ]"
elif [ -n "${FILES_DEBIAN}" ]; then
  echo "Detected Debian source files: ${FILES_DEBIAN}"
  echo
  echo "[ running source build ]"
  icinga-build-deb-source
  if [ $? -ne 0 ]; then
    echo "[ source build failed! ]"
    exit 1
  fi
  echo "[ source build completed ]"
  echo

  echo "[ running binary build ]"
  icinga-build-deb-binary
  if [ $? -ne 0 ]; then
    echo "[ binary build failed! ]"
    exit 1
  fi
  echo "[ binary build completed ]"
else
  echo "Could not detect build type!" >&2
  exit 1
fi
